apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  releaseName: jenkins 
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: jenkins
    version: 1.1.12
